---
- name: install and configure KVM server
  hosts: kvm
  vars:
    kvm_hostname_full: "{{ ansible_fqdn }}"
  vars_files:
    - extra_vars.yml
  become: yes
  tasks:
  
  - name: register and subscribe server
    redhat_subscription:
      state: present
      username: "{{ portal_username }}"
      password: "{{ portal_password }}"
      auto_attach: true
  
  - name: Disable all RHSM repositories
    rhsm_repository:
        name: '*'
        state: disabled

  - name: enable repository for KVM installation
    rhsm_repository:
      name: 
        - rhel-7-server-rpms
        - rhel-7-server-ansible-2.9-rpms
      state: enabled 

  - name: Update hole system to latest version
    yum:
      name: '*'
      state: latest

  - name: Install prerequiments
    yum:
      name:
        - screen
        - vim
        - sos
        - git
        - ansible
      state: latest

#  - name: Install Roles prerequirments
#    local_action:
#      command: ansible-galaxy install -r requirements.yml

  - name: Deploy kvm
    include_role:
      name: redhatgov.kvm

- name: Create VM on kvm 
  hosts: kvm
  become: yes
  tags: provision
  vars:
    kvm_vm_hostname: "satellite.example.com"
    kvm_vm_public_ip: 192.168.122.10
    kvm_vm_root_pwd: "p@ssw0rd"
    kvm_vm_base_img: rhel-guest-image-7.qcow2
    kvm_vm_vcpus: "1"
    kvm_vm_ram: "2048"
    kvm_vm_os_disk_name: "{{ kvm_vm_hostname }}"
    kvm_vm_os_disk_size: "10G"
    kvm_vm_nics:
        name: eth0
        bootproto: static
        onboot: yes
        ip: "{{ kvm_vm_public_ip }}"
        prefix: "24"
        gateway: "192.168.122.1"
        dns_server: "192.168.122.1"
        config: "--type network --source default --model virtio"
  tasks:
    - name: Create KVM VM
      include_role:
        name: ansible-kvm-vm
